# Copyright lowRISC contributors.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

name: Create Release

on:
  workflow_dispatch:
    inputs:
      release_tag:
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y $(find . -name apt-requirements.txt | xargs sed -e "s/#.*//g")
      - name: Create tag
        run: |
          git tag "${{ inputs.release_tag }}"
          git push origin tag "${{ inputs.release_tag }}"
      - name: Build firmware
        run: |
          bazel build --stamp :hyperdebug-firmware
      - name: Publish Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create "${{ inputs.release_tag }}" \
            --title "${{ inputs.release_tag }}"
          gh release upload "${{ inputs.release_tag }}" \
            "$(bazel cquery --output=files :hyperdebug-firmware)"
